Add proposed dates for the rest of the year to the top-level README
tc39/agendas pull request #1295
Opened 2023-01-06 00:09 UTC by tabatkins

2023-01-06 00:12 UTC, ljharb requested changes
This is in an autogenerated section of the readme (`npm run build`); it also would create a secondary source of truth that needs updating, so i'm not sure it's the best place to put it.

2023-01-06 00:14 UTC, ljharb commented
Although maybe we should move it to the readme _above_ the autogenerated section, and remove it from the agendas themselves (and replace them with a link to the readme section)?

2023-01-06 00:51 UTC, tabatkins commented
Ah, had no idea it was auto-genned, but now that comment in the source makes sense. I've moved the table to its own details above the auto-gen section for now; we can think about exposing this information to the autogen later.

2023-01-06 04:03 UTC, ljharb commented
Sounds great! Can you also remove the table from the template and the January agenda, and make both link to the new table in the readme?

2023-01-06 18:08 UTC, michaelficarra commented
Also, the January meeting is still upcoming!

2023-01-06 18:44 UTC, tabatkins commented
Jan meeting is upcoming, but confirmed and with its own page already, so it doesn't go in the "proposed" table. ^_^

2023-01-06 20:23 UTC, jridgewell commented
> Jan meeting is upcoming, but confirmed and with its own page already, so it doesn't go in the "proposed" table. ^_^

I would make this a "future meetings" section instead of a "**tentatively planned** future meetings", with a "confirmed" field on the table

2023-02-01 20:25 UTC, tabatkins commented
I added a "Confirmed" column, but since I waited so long, the Jan meeting is no longer upcoming at all. ^_^

2023-02-01 20:32 UTC, ljharb commented on README.md
> +|           | 2023-03-21 to 2023-03-23 | Seattle, US         | F5                   |
i think this one's pretty confirmed

2023-02-02 19:38 UTC, tabatkins commented
Cool, put a checkmark in its row now

2023-02-02 19:47 UTC, jridgewell approved these changes

2023-02-02 19:50 UTC, merged