Notes disclaimer
tc39/agendas pull request #1424
Opened 2023-07-05 19:51 UTC by littledan

https://github.com/tc39/Reflector/issues/460

2023-07-05 19:54 UTC, ljharb approved these changes
Looks fine, but it seems to be equally applicable with the stenographer, or with all previous meetings where notes were taken.

2023-07-05 20:00 UTC, ljharb commented
hmm, 539aaf0e is already pushed to main. i'll force push it out since this PR seems the same.

2023-07-05 20:04 UTC, ctcpip commented
> including deleting comments which you do not wish to appear

perhaps there could be some clarified guidance on this item.  I have seen others delete comments that would be relevant to have in the notes.  could this perhaps be updated to language that limits this to one's own comments?  in practice of course, there is discretion in all these things, but maybe the existing language is too broad?

2023-07-05 20:53 UTC, littledan commented
An alternative is that we could include the full text that I posted on the Reflector. Either way, Patrick from Ecma wants us to say something here because he imagines there is a GDPR compliance risk (though I am not so convinced).

2023-07-05 21:19 UTC, ctcpip commented
Technically, GDPR does apply, and neither this disclaimer nor the text you posted on the Reflector brings us into GDPR compliance.  If the issue is GDPR compliance, we can attempt to solve for that, but again, this note doesn't move the needle at all on GDPR.

2023-07-05 21:20 UTC, ctcpip commented
@tc39/chairs we need to discuss this

2023-09-15 08:38 UTC, littledan commented
What are next steps on this PR?

2023-09-21 07:23 UTC, littledan commented
It already lives in a Reflector issue. Landing the text here is a request of the Ecma Secretariat to serve GDPR concerns (possibly out of a misplaced excess of caution). But explaining notes is also a practical thing, and probably of interest to more people than the agenda rules always being copy-pasted.

I recommend the people who want to reject the Secretariat's advice to take it up with that group. If no one is going to do that, let's just land this patch; it really doesn't cause any harm.

2023-09-21 14:38 UTC, ctcpip requested changes

2023-09-21 14:38 UTC, ctcpip commented on template.md
> +    1. Note: A detailed transcript of the meeting is being prepared and will be eventually posted on GitHub. You may edit this at any time during the meeting in Google Docs for accuracy, including de
can we do this?  deleting is included in "editing" and resolves my concerns in a previous comment

2023-09-21 15:36 UTC, littledan commented on template.md
> +    1. Note: A detailed transcript of the meeting is being prepared and will be eventually posted on GitHub. You may edit this at any time during the meeting in Google Docs for accuracy, including de
We are specifically supposed to include deletion here.

2023-09-21 15:37 UTC, littledan commented
@ljharb Yes, this is the intention, to announce at the beginning of the meeting alongside it being in written form here. Let me know if you have suggestions for how the written text should be edited.

2023-09-21 15:38 UTC, ljharb commented
I think a short summary is fine; the actual announcement shouldn’t be inline.

2023-09-21 20:48 UTC, ctcpip commented on template.md
> +    1. Note: A detailed transcript of the meeting is being prepared and will be eventually posted on GitHub. You may edit this at any time during the meeting in Google Docs for accuracy, including de
I've updated the suggested to change; does that work?

2023-09-21 20:51 UTC, ljharb requested changes
being explicit that the content of this announcement doesn't belong on the agenda; a short summary would be fine. the content, if anywhere, belongs only on the reflector and/or on the notes docs, not here, since the agenda is for public consumption.

2023-09-22 16:52 UTC, robpalme approved these changes

2023-09-22 16:52 UTC, merged

2023-09-22 18:31 UTC, ljharb commented
@ctcpip this doesn't resolve my concerns because the content is still on the agenda. using a `<details>` doesn't change that. PRs shouldn't ever be merged through blocks - I've pushed a commit that implements https://github.com/tc39/agendas/pull/1424#discussion_r1333602606; feel free to open a PR if that's problematic.

2023-09-22 19:47 UTC, ctcpip commented
my apologies.  we discussed and merged and had yet to add a comment here re: best way to proceed.  in any case, I've reached out to Samina to get clarification on what their specific ask is (can we simply link to the text, etc), and next steps on wordsmithing.